In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

In [19]:
df = pd.read_csv("Data/ESPA_Deltas_All_Rounds.csv", low_memory=False)

FileNotFoundError: [Errno 2] No such file or directory: 'Data/ESPA_Deltas_All_Rounds.csv'

In [12]:
lands = pd.read_excel("ESPA_DELTAS_LAND_COVER.xlsx", header=4)
listing = pd.read_csv("ESPA_Deltas_Listing.csv")

In [14]:
df

,IDNO,CLUSTER,ZONE,DIVISION,DISTRICT,UPAZILA,UNION,MOUZA,SEGMENT,HNUMBER,...,Q1713D,Q1714H,Q1714M,Q503_1,Q503_2,Q503_3,Q503_4,Q1407H,Q1407M,IDNOR
0,1005,1,1,1,6,36,81,356,1,5,...,2,10,59,,,,,,,10053
1,1010,1,1,1,6,36,81,356,1,10,...,2,12,10,,,,,,,10103
2,1012,1,1,1,6,36,81,356,1,12,...,2,17,9,,,,,,,10123
3,1015,1,1,1,6,36,81,356,1,15,...,2,14,18,,,,,,,10153
4,1018,1,1,1,6,36,81,356,1,18,...,2,13,15,,,,,,,10183
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4753,63130,63,7,4,47,30,67,852,4,130,...,,,,,,,,13,58,631301
4754,63131,63,7,4,47,30,67,852,4,131,...,,,,,,,,14,50,631311
4755,63135,63,7,4,47,30,67,852,4,135,...,,,,,,,,16,2,631351
4756,63139,63,7,4,47,30,67,852,4,139,...,,,,,,,,10,7,631391
4757,63141,63,7,4,47,30,67,852,4,141,...,,,,,,,,16,20,631411